# Generated by Django 3.2.5 on 2022-03-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=256, unique=True)),
                ('course_name_slug', models.SlugField(default='', max_length=256, primary_key=True, serialize=False, unique=True)),
                ('lec_image', models.ImageField(upload_to='static/images/uploads/')),
            ],
        ),
    ]
