# Generated by Django 3.2.5 on 2022-03-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lec_image',
            new_name='course_image',
        ),
    ]
