# Generated by Django 3.2.5 on 2022-03-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_lec_image_course_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=256)),
                ('video_url', models.URLField()),
                ('video_image', models.ImageField(upload_to='static/images/uploads/')),
                ('video_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.course')),
            ],
        ),
    ]
