# Generated by Django 3.2.5 on 2022-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lec_name', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(default='', max_length=256, primary_key=True, serialize=False, unique=True)),
                ('lec_image', models.ImageField(upload_to='static/images/uploads/')),
                ('lec_description', models.TextField(null=True)),
            ],
        ),
    ]
