# Generated by Django 3.2.5 on 2022-03-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20220320_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='static/images/uploads/'),
        ),
    ]
